name: Pre-Commit

on: ["push", "pull_request"]

jobs:
  Pre-Commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    container:
      image: python:3.9-slim-buster

    steps:

      - name: Install System Deps
        run: |
          apt-get update
          apt-get install -y enchant git

      - uses: actions/checkout@v2

      - name: Install Pre-Commit
        env:
          PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install --install-hooks

      - name: Check ALL Files
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
